### ISSUE TITLE
Error 33804 Again :(

### ISSUE THREAD

**Issue by majidorc** [the-lazy-fox/script.tvtime#13]
Hello , any update ?

**Comment by nonobio** [comment]
Hello,

Same error for me with TV Time 1.2.4 and Kodi 18.9 on Windows 7.

Thanks

**Comment by davidkast** [comment]
Hi,
Same error for me with TV Time 1.2.4 and Kodi 18.9 on Chromecast Google TV.
Thanks.

**Comment by GofranAy** [comment]
Go to tv time ask if they can fix the link api.tvtime.com they disabled it or are checking i dont know but as long as this link not working app wont work also

**Comment by GofranAy** [comment]
I asked tvtime support this is what they said 
we've asked our dev team re: the API. We'll let you know when we hear back.
But as we ask more maybe they will check faster

**Comment by nonobio** [comment]
Hi,

I also had a reply from support : 

> We've been made aware that our public API is not working as expected. This may cause issues with your calendar, 3rd party app syncing, as well as using TV Time Google Chrome extension.
We've escalated this issue to our dev team for further investigation. We'll let you know as soon as we have an update on the issue.
We're sorry for the inconvenience, but we'll get back to you as soon as we have an update.

**Comment by eraser-head** [comment]
any news?

**Comment by panizza** [comment]
https://api.tvtime.com/ is working, but error 33804 is still there

**Comment by GofranAy** [comment]
> https://api.tvtime.com/ is working, but error 33804 is still there

Maybe reinstall for me its working now

**Comment by panizza** [comment]
Try this https://github.com/the-lazy-fox/script.tvtime/pull/12
We fixed the login issue and other problems

**Comment by davidkast** [comment]
> Try this #12
> We fixed the login issue and other problems

Perfect, it already works !!

**Comment by the-lazy-fox** [comment]
Fixed in v2.0.0
https://github.com/the-lazy-fox/script.tvtime/releases/tag/v2.0.0

**Comment by majidorc** [comment]
did you get error 33804 again ?

**Comment by enrique131** [comment]
I have the error 33804 again. I reinstall the addon and issue persists

**Comment by panizza** [comment]
> I have the error 33804 again. I reinstall the addon and issue persists

Yeah, tvtime have some issues. Again, it's not a plugin issue. Always visit api.tvtime.com before opening an issue or comment

**Comment by majidorc** [comment]
> > I have the error 33804 again. I reinstall the addon and issue persists
> 
> Yeah, tvtime have some issues. Again, it's not a plugin issue. Always visit api.tvtime.com before opening an issue or comment

I see, thank you.
